implement splitting/extracting block log for eosio_blocklog
EOSIO/eos pull request #10037
Opened 2021-02-12 15:15 UTC by huangminghuang

## Change Description

implement splitting/extracting block log for eosio_blocklog

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ ] Stability bug fix

- [x] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [ ] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [x ] Documentation Additions
`eosio_blocklog` added two new options
   - split-blocklog: split the block log file based on the stride and store the result in the specified 'output-dir'
   - extract-blocklog: extract blocks from blocks.log and blocks.index and keep the original .

2021-02-12 22:43 UTC, matthewdarwin commented
Documentation related comments:

1) Can you use this tool to change take existing strides and make them smaller?
2) Can you use this tool to change take existing strides and make them bigger?
3) What happens when the input is part of the block log (eg existing blocks split in strides is missing one of the strides)?

Or does this tool strictly work only with the full block.log file?

2021-02-15 14:14 UTC, huangminghuang commented
> Documentation related comments:
> 
> 1. Can you use this tool to change take existing strides and make them smaller?
> 2. Can you use this tool to change take existing strides and make them bigger?
> 3. What happens when the input is part of the block log (eg existing blocks split in strides is missing one of the strides)?
> 
> Or does this tool strictly work only with the full block.log file?

So far, it only works with full block.log file. For more complex stride adjusting, it should be implemented as script instead of in the eosio_blocklog tool.

2021-02-15 17:18 UTC, brianjohnson5972 requested changes

2021-02-15 21:18 UTC, huangminghuang commented on libraries/chain/block_log.cpp
> +         uint32_t num_blocks = std::min(stride, last_block_num - start_block_num + 1);
You were looking at outdated code

2021-02-16 19:48 UTC, brianjohnson5972 approved these changes

2021-02-16 20:13 UTC, merged