Ensure container.size() > 0 before initiating RocksDB writes/deletes
EOSIO/eos pull request #10276
Opened 2021-04-20 19:24 UTC by nksanthosh

## Change Description

In the prior implementation RocksDB writes/deletes were always called even if the input size was zero. Added a check to only send those calls to rocksDB when size()>0. Improved performance of replays marginally. These zero sized calls to rocksDB numbered many thousands in 1M blocks replays of real world blockslogs.

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ ] Stability bug fix

- [x] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [ ] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2021-04-20 19:28 UTC, heifner requested changes

2021-04-20 19:28 UTC, heifner commented on libraries/chain_kv/include/b1/session/session.hpp
> +
Fix indentation

2021-04-21 21:21 UTC, linhuang-blockone approved these changes

2021-04-23 18:40 UTC, brianjohnson5972 approved these changes

2021-04-23 18:42 UTC, merged