Addition of a Transaction Extension to Control Payment for Resources
EOSIO/eos pull request #10407
Opened 2021-05-28 14:50 UTC by ndcgundlach

Addition of a Transaction Extension to Control Payment for Resources

Added a new transaction extension which allows the specification of a bill to account and maximum cpu and net to be charged for the transaction.
## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ ] Stability bug fix

- [x ] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [ x] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2021-06-01 17:06 UTC, jgiszczak requested changes
Merge conflicts and test failures.

2021-06-04 15:47 UTC, ndcgundlach commented on libraries/chain/authorization_manager.cpp
> +         permissions_to_satisfy.emplace(permission_level{payer->payer, config::active_name},effective_provided_delay);
I added a Jira item to review the options for this as it was not part of original spec.

2021-06-04 17:24 UTC, ndcgundlach commented
> Merge conflicts and test failures.

fixed

2021-06-07 15:08 UTC, jgiszczak approved these changes

2021-06-07 16:18 UTC, merged