Feature privacy with blockvault test
EOSIO/eos pull request #10441
Opened 2021-06-18 21:48 UTC by shahabi8

This PR creates a Python test for feature privacy with blockvault. There is a nodeos cluster with three nodes, two of them has access to blockvault. Security group is introduced to restrict non-participant node access to produced blocks as well as change of password for postgres database such that the non-participant nodes cannot retrieve data from blockvault.

## Change Type
**Select *ONE*:**
- [x] Documentation

- [ ] Stability bug fix

- [ ] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [x] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [x] Documentation Additions
It should be mentioned that security group does not restrict non-participant nodes access to blockvault. Postgres login credentials need to get updated to restrict non-participant nodes access.

2021-06-19 16:57 UTC, dimas1185 commented on tests/feature_privacy_blockvault.py
> +    cluster.setWalletMgr(walletMgr)
you can save 2 lines and initialize wallet manager inside Cluster constructor

2021-06-19 17:02 UTC, dimas1185 commented on tests/feature_privacy_blockvault.py
> +    Print("### change postgre password to restrict node 2 access to it ###")
my understanding of blockvault feature is that it is used to create a cluster with same producer key with backup instances. Hence all of it's instances supposed to have same password and same certificate. So I don't see much logic in the scenario you are testing. Correct me if I missed something.

2021-06-19 17:09 UTC, dimas1185 requested changes
two things:
1. please add more comments, test description, similar to the one in PR and ideally comment every step. this is essential for other people to maintain your test or solve flakyness if it will appear.
2. please review your test scenario, see my comment on line 123

2021-11-11 15:33 UTC, shahabi8 commented
Closed this PR. Blockvault is not supposed to use this way.

2021-11-11 15:33 UTC, closed without merging