support creating TPM keys at a specific persistent handle 📦
EOSIO/eos pull request #10812
Opened 2021-10-14 02:47 UTC by spoonincode

## Change Description

Prior to this change, `eosio-tpmtool` would persist created keys at the first available owner handle in the TPM. This simplicity is nice to avoid exposing details of TPM handles to users, but sometimes it can cause deployment headaches. Consider a boot or deployment script that always wants to create a BP key if it doesn't already exist. Using something like `eosio-tpmtool --list | wc` isn't always helpful because `eosio-tpmtool --list` will report all usable TPM keys: even keys it did not create itself -- keys that may used for other purposes -- making it hard to correlate the number of existing keys with whether a BP key needs to be created.

Instead of requiring the environment to further parse the output of `eosio-tpmtool -l` to determine if it needs to create a key, add the ability for `eosio-tpmtool` to persist to a specific handle. If that handle already has an object persisted there, the command will fail with error code 100. This allows a deployment script to do something like
```bash
bp_key_handle=0x81000E05

if key=$(./eosio-tpmtool --create --handle $bp_key_handle); then
   echo created BP key: $key
   # do something more interesting here, like upload the key somewhere or modify nodeos config.ini
elif [[ $? == 100 ]]; then
   echo BP key was already created
   # no need to do interesting things here
else
   echo eosio-tpmtool failed
fi
```

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ ] Stability bug fix

- [x] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [x] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2021-10-14 12:20 UTC, heifner requested changes

2021-10-14 12:20 UTC, heifner commented on programs/eosio-tpmtool/main.cpp
> +      ("handle", bpo::value<std::string>()->notifier([&](const std::string& a) {
Is there a reason to use `std::string` and convert to long instead of just `bpo::value<uint32_t>` ?

2021-10-14 14:02 UTC, spoonincode commented on programs/eosio-tpmtool/main.cpp
> +      ("handle", bpo::value<std::string>()->notifier([&](const std::string& a) {
I want to allow passing the parameter as hex, e.g. 0x81000E05. I seem to recall that doesn't work if it just using uint32_t here, where strtol() is smart enough to autodetect the leading 0x if one exists. I can double check; been a long time maybe I'm misremembering.

2021-10-15 15:20 UTC, spoonincode commented on programs/eosio-tpmtool/main.cpp
> +      ("handle", bpo::value<std::string>()->notifier([&](const std::string& a) {
Yes a simple boost program options driver:
```c++
         uint32_t bananas = 0;

         cli.add_options()
                 ("bananas", bpo::value<uint32_t>(&bananas), "Number of bananas");

         bpo::variables_map varmap;
         bpo::store(bpo::parse_command_line(argc, argv, cli), varmap);
         bpo::notify(varmap);

         std::cout << "number of bananas: " << bananas << std::endl;
```
yields:
```
$ ./dk --bananas 256
number of bananas: 256
$ ./dk --bananas 0x100
terminate called after throwing an instance of 'boost::wrapexcept<boost::program_options::invalid_option_value>'
  what():  the argument ('0x100') for option '--bananas' is invalid
```

Allowing hex input for these values is important, since persistent key handles are defined by the TPM spec as being 0x81xxxxxx, so you'd almost always enter handles manually in hex.

2021-10-15 15:24 UTC, heifner commented on programs/eosio-tpmtool/main.cpp
> +      ("handle", bpo::value<std::string>()->notifier([&](const std::string& a) {
Thanks for the clarification.

2021-10-15 15:25 UTC, heifner approved these changes

2021-10-15 20:22 UTC, merged