allow empty table 📦
EOSIO/eos pull request #10833
Opened 2021-10-24 21:27 UTC by huangminghuang

## Change Description

This PR allows the `get_kv_table_rows` api endpoint to accept empty table value. In this case, the result rows would return a vector of key and data which contains the hex string of the key and data.
 

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ ] Stability bug fix

- [ ] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [ ] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2021-10-24 21:39 UTC, linhuang-blockone commented on plugins/chain_plugin/chain_plugin.cpp
> +         return fc::mutable_variant_object("data", std::move(result))("key", get_key_hex_string());
Is `result` in hex format?

2021-10-25 00:44 UTC, linhuang-blockone approved these changes

2021-10-25 12:36 UTC, heifner requested changes

2021-10-25 12:36 UTC, heifner commented on plugins/chain_plugin/chain_plugin.cpp
> +      else if (context.p.table.empty()) {
Shouldn't this be an `if` instead of an `else if`

2021-10-25 15:46 UTC, heifner approved these changes

2021-10-25 15:49 UTC, merged