Huangminghuang/epe-1646-min-initial-block
EOSIO/eos pull request #10872
Opened 2021-11-03 18:18 UTC by huangminghuang

## Change Description

This PR adds `min-initial-block-num` option to chain plugin so that nodeos could refuse to load any state from prior to the specified block number

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ ] Stability bug fix

- [ ] Other

- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [ ] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2021-11-03 18:29 UTC, heifner commented on libraries/chain/controller.cpp
> +      "at block number ${block_num}, which is smaller than the minimum required ${required}", ("block_num", fork_db.head()->block_num)("required",this->conf.min_initial_block_num) );
This reports and uses the term head when lib is used. Also the variable name and option description should be clear that this feature is for lib and not head.

2021-11-03 18:29 UTC, heifner requested changes
lib vs head comment.

2021-11-03 20:14 UTC, nksanthosh reviewed
Will the implementation work with all 4 options (irrespective of how state is loaded)

1. Replay
2. From genesis
3. Snapshot
4. Load binary state file

Has it been manually tested against all 4 options?

Either add automated tests for all four options if it is quick or we can prioritize and add automated tests as a separate PR immediately following this one.

2021-11-03 21:01 UTC, huangminghuang commented
> Will the implementation work with all 4 options (irrespective of how state is loaded)
> 
> 1. Replay
> 2. From genesis
> 3. Snapshot
> 4. Load binary state file
> 
> Has it been manually tested against all 4 options?
> 
> Either add automated tests for all four options if it is quick or we can prioritize and add automated tests as a separate PR immediately following this one.

Unit tests are available to test against each scenario.

2021-11-03 21:51 UTC, linhuang-blockone commented on libraries/chain/controller.cpp
> +      "at block number ${lib_num}, which is smaller than the minimum required ${required}", ("block_num", lib_num)("required",this->conf.min_initial_block_num) );
"block_num" should be "lib_num"

2021-11-03 21:51 UTC, victorj8 commented on libraries/chain/controller.cpp
> +      "at block number ${lib_num}, which is smaller than the minimum required ${required}", ("block_num", lib_num)("required",this->conf.min_initial_block_num) );
I think this should be ${block_num} instead of ${lib_num}

2021-11-04 13:12 UTC, linhuang-blockone commented on unittests/restart_chain_tests.cpp
> +   // restarting chain with no block log and no genesis
Can you add a test for normal cases `lib == cfg.min_initial_block_num`  and `lib > cfg.min_initial_block_num`?

2021-11-04 18:34 UTC, linhuang-blockone approved these changes

2021-11-04 18:49 UTC, heifner commented on plugins/chain_plugin/chain_plugin.cpp
> +         "nodeos would refuse to load any state from prior to that block number")
Should not use hard coded "nodeos". Either don't mention "nodeos" or use the executable name variable. I prefer just not mentioning it. Also I think it should be "will" not "would".

Maybe something like:
"minimum last irreversible block (lib) number, fail to start if state/snapshot lib is prior to specified"

2021-11-04 19:49 UTC, heifner approved these changes

2021-11-05 15:41 UTC, nksanthosh approved these changes

2021-11-05 16:42 UTC, merged