Fix intermittent failure in nodeos_high_transaction_test.py
EOSIO/eos pull request #10878
Opened 2021-11-05 20:19 UTC by nickjjzhao

2021-11-08 13:56 UTC, heifner requested changes

2021-11-08 13:56 UTC, heifner commented on tests/nodeos_high_transaction_test.py
> +                    node.waitForTransInBlock(transId, timeout = args.transaction_time_delta + 10)
Instead of adding 10 here, change `--transaction-time-delta` default from 5 to 15.

2021-11-11 13:43 UTC, heifner approved these changes

2021-11-15 15:52 UTC, nickjjzhao commented
Superseded by [PR#10884](https://github.com/EOSIO/eos/pull/10884).

2021-11-15 15:52 UTC, closed without merging