Added deduplication headers to rodeos rabbit stream
EOSIO/eos pull request #10871
Opened 2021-11-03 16:47 UTC by ndcgundlach

Added deduplication headers to rodeos rabbit stream

Updated the transactional amqp publisher to optionally add the x-deduplication-header to enable the de-duplication of messages.  Rodeos set the option to true.

## Change Type
**Select *ONE*:**
- [ ] Documentation

- [ ] Stability bug fix

- [ x] Other
performance improvement
- [ ] Other - special case

## Testing Changes
**Select *ANY* that apply:**
- [ ] New Tests

- [ ] Existing Tests

- [ ] Test Framework

- [ ] CI System

- [ ] Other

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2021-11-03 17:11 UTC, linhuang-blockone commented on libraries/amqp/transactional_amqp_publisher.cpp
> +      AMQP::Table headers;
A minor one. You can move this declaration inside the if statement below.

2021-11-03 17:16 UTC, linhuang-blockone approved these changes
How easy to add a test to it?

2021-11-09 01:37 UTC, heifner commented on tests/rodeos_rabbit_test.py
> +# Lastly, it verifies if rodeos get_info endpoint returns a head_block_num.
Update this comment.

2021-11-09 01:41 UTC, heifner requested changes

2021-11-09 01:41 UTC, heifner commented on tests/rodeos_rabbit_test.py
> +            # Test sigkill restart
Why include sigkill in this test?

2021-11-09 01:41 UTC, heifner commented on tests/rodeos_rabbit_test.py
> +###############################################################
I don't see how this tests de-dup of streamed rabbit messages. Please explain.

2021-11-11 14:26 UTC, heifner commented on programs/rodeos/streams/rabbitmq.hpp
> -      if( error ) return;
I guess we don't currently have any tests that needed this. In the future any streaming test will need to create the queue manually.

2021-11-11 14:26 UTC, heifner approved these changes

2021-11-12 14:53 UTC, merged