Implement blockvault client plugin
EOSIO/eos pull request #9652
Opened 2020-11-10 17:42 UTC by huangminghuang

## Change Description
This PR implements the client communication between nodeos and postgres for block vault 

## Change Type
**Select ONE**
- [ ] Documentation

- [ ] Stability bug fix

- [x] Other

- [ ] Other - special case

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2020-11-10 22:27 UTC, heifner requested changes
Not done reviewing, but done for the day.

2020-11-10 22:27 UTC, heifner commented on plugins/blockvault_client_plugin/scope_exit.hpp
> +#pragma once
fc already has a `scoped_exit`, use it.

2020-11-11 16:20 UTC, heifner requested changes

2020-11-11 16:20 UTC, heifner commented on plugins/blockvault_client_plugin/tests/temporary_file.hpp
> +};
Should be able to use `fc::temp_file`

2020-11-11 17:38 UTC, huangminghuang commented on plugins/blockvault_client_plugin/postgres_backend.cpp
> +   w.exec("CREATE TABLE IF NOT EXISTS BlockData (watermark_bn bigint, watermark_ts bigint, lib bigint, "
In postgres, `integer` is signed 32 bits. There is no unsigned 32 bits integer.

2020-11-11 17:45 UTC, heifner commented on plugins/blockvault_client_plugin/postgres_backend.cpp
> +   w.exec("CREATE TABLE IF NOT EXISTS BlockData (watermark_bn bigint, watermark_ts bigint, lib bigint, "
Right. So the question is do we care about 2^31 - 2^32 block #s? 34 years is a long time from now and it will take that long to hit 2^31.

2020-11-11 20:31 UTC, heifner commented on plugins/blockvault_client_plugin/postgres_backend.cpp
> +   w.exec("CREATE TABLE IF NOT EXISTS BlockData (watermark_bn bigint, watermark_ts bigint, lib bigint, "
Talked. Agree this hardly makes much diff when storing blocks and snapshots. Going to go with `bigint` so it is future proof.

2020-11-11 20:33 UTC, heifner submitted a review, later dismissed

2020-11-13 17:13 UTC, merged