Add integration test
EOSIO/eos pull request #9711
Opened 2020-11-24 15:06 UTC by huangminghuang

## Change Description

This PR adds block vault integration test and fix some issues/improvements discovered by the test.

Issues Fixed:
  1.  Allow unlinkable blocks received from block vault to be ignored.
  2. Sync only returns the blocks having greater watermark than the snapshot instead of greater or equal than.
  3. Ignore append_external_block during sync

Improvements:
  1. Fix the libpq, libpqxx install versions for pinned ci script on Mac
  2. Better diagnostic messages.

## Change Type
**Select ONE**
- [ ] Documentation

- [ ] Stability bug fix

- [x] Other

- [ ] Other - special case

## Consensus Changes
- [ ] Consensus Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

2020-11-25 17:14 UTC, heifner requested changes

2020-11-25 17:14 UTC, heifner commented on tests/blockvault_tests.py
> +    Print("# Scenario 3: Test two identical producer nodes conneting to the block vault    #")
"connecting"

2020-11-25 17:55 UTC, ndcgundlach approved these changes

2020-11-25 20:46 UTC, heifner approved these changes

2020-11-26 15:42 UTC, heifner submitted a review, later dismissed

2020-11-30 23:42 UTC, merged